# Generated by Django 5.1.1 on 2025-01-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('number', 'anime')},
        ),
    ]
