# Generated by Django 5.1.1 on 2025-01-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_list', '0002_alter_episode_number_alter_episode_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
