# Generated by Django 5.1.1 on 2025-01-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_list', '0003_alter_anime_id_alter_episode_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set(),
        ),
    ]
