# Generated by Django 5.1.1 on 2025-01-17 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=400)),
                ('type', models.CharField(choices=[('anime', 'Anime Canon'), ('manga', 'Manga Canon'), ('filler', 'Filler'), ('mixed', 'Mixed Canon/Filler')], max_length=50)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
