# Generated by Django 5.1.1 on 2025-02-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_anime_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
